# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('likes', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Question name')),
                ('content', models.CharField(max_length=500, verbose_name='Question content')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Question in archive')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='questions', to='categories.Category', verbose_name="Question's categories")),
                ('comments', models.ManyToManyField(blank=True, related_name='question_comments', to='comments.Comment', verbose_name="Question's comments")),
                ('likes', models.ManyToManyField(blank=True, related_name='question_likes', to='likes.Like', verbose_name="Question's likes")),
            ],
            options={
                'ordering': ('name', 'id'),
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
