# Generated by Django 2.1.3 on 2018-11-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
