# Generated by Django 2.1.3 on 2018-11-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20181020_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
