version: "2.1"
services:
        db:
                image: mysql
                restart: always
                ports: [ '3306:3306' ]
                volumes: [ 'mysqldata:/var/lib/mysql' ]
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_USER: stack
                        MYSQL_PASSWORD: stack
                        MYSQL_DATABASE: stack_db
        stackoverflow:
                depends_on: [db]
                build:
                        context: .
                        dockerfile: Dockerfile
                image: stackoverflow
                volumes: [ '.:/app' ]
                ports: [ '8000:8000' ]
                environment:
                        DB_NAME: stack_db
                        DB_HOST: db
                        DB_USER: stack
                        DB_PASSWORD: stack
volumes:
        mysqldata:
                external: true
                name: mysqldata
