# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181020_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=1, max_length=500, verbose_name='Comment content'),
            preserve_default=False,
        ),
    ]
